### ISSUE TITLE
Should the "counting" models start on 0 or -1

### ISSUE THREAD

**Issue by taylorbf** [taylorbf/Musicians-Toolkit#32]
Michael, 

In brief --

I'm re-raising this question b/c I haven't exactly found a pretty way to do it. This would apply to Counter and Sequence.

I want the use pattern for these models to look something like this --

```
counter = mt.counter(0,10);

mt.time.interval( 100, function() {
   console.log( counter.next() );
})
```

Results in

```
0
1
2
3
4
5
etc...
```

That's a little pointless / abstract, so let's get concrete:

```
// Create the melody for twinkle twinkle little star
melody = mt.sequence([ 48, 48, 55, 55, 57, 57, 55, 0 ]);

mt.time.interval( 300, function() {
   synth.frequency.value = melody.next();
})
```

So the use case is really to call .next() every time you want to get a digit. And if we start the position at 0, that means we miss the first value in the above example.

I don't like the idea of needing to set the value as an argument
```
melody = mt.sequence([ 48, 48, 55, 55, 57, 57, 55, 0 ],"up", -1);
```

Nor do I like the idea of needing to set it with an extra line of code.

```
melody = mt.sequence([ 48, 48, 55, 55, 57, 57, 55, 0 ]);
melody.prev();    // or melody.pos = -1
```

So really, I like the concept of starting at -1. The only trouble with it is the following example:

```
melody = mt.sequence([ 48, 48, 55, 55, 57, 57, 55, 0 ]);
console.log( melody.value );  // throws an error -- can't read index -1 of the sequence array
```

So I'm thinking maybe the best way out of this is simply to hard-code some exception for when the model is newly created? Like, manually set .value to be the first item in the array. There will be some dissonance because .value will be item 0, and .pos will be -1 .... It's a little ugly. But maybe worth it?

Not a big deal but wanted to keep you in the loop about this!

**Comment by taylorbf** [comment]
@mscottnelson forgot to tag you so github sends you a ping about this one : )

**Comment by mscottnelson** [comment]
I'd set a new Boolean e.g. "newSequence", have it flip after it gets used.
Next and prev should both look for it so they behave consistently. This
way, even if the starting position isn't 0, it will still start on whatever
value the user specified. I would do this myself now but I'm on mobile

**Comment by mscottnelson** [comment]
Actually should probably follow a naming convention more like "sequenceNew

**Comment by taylorbf** [comment]
Yes that is a possibility -- we'd need to add an if statement in the .next() and .prev() methods, and that if statement will only be useful once, right? I mean it's not the end of the world to have an extra "if" in there but I'd like to avoid it.

You bring up a great point though that .prev() will also need to work correctly on the first time, as will next/prev in other modes! So the -1 solution isn't great either. 

I don't mind implementing this-- I'm going through every file this week anyway.

**Comment by mscottnelson** [comment]
You want it to behave differently on the first run only. The might be
another design pattern that makes sense but I'm not thinking of it. I guess
another way of thinking about this is "hasReceivedInput," so that things
might function differently if they are set to a particular state vs whether
a state change has been requested. I think you'd be looking at a lot more
confusing complexity with that kind of a design pattern, however. Another
generalizable choice might be to have next() output current state before
updating the internal state. I suppose the downside there is that the
reported value will be different than the currently held value, always...I
think reporting the "past" in this way is also going to end up being more
confusing than helpful, even though it would result in more consistency
than giving "new" things a special status.

**Comment by taylorbf** [comment]
Oh! 

> You want it to behave differently on the first run only.

Yes! That is a great way to express it. Thanks for talking through this with me. I think I have an idea now ... We can assign .next to one function at the beginning, and have *that* function set .next to be .up or .down or whatever. I'll add this in -- should only be a small change. The models are great -- I have been very consciously designing the API this week and it has led to some small changes like this across all the interfaces as well.

B
